unique_ids:
  assets:
    Screenshot 2025-08-21 141532.png: '1755749744483680169885659.3'
    standard-page.html: K5NDDVFTUSQUYQUMVSWGI7PZXCVZ7ION
    theme.css: QOKZG64PQWIPIUZQ44T3HUURVA435PCR
  forms:
    Form1: OCMXIEGJPCN5GB3H7M7DXDBXTUGTEK4U
  modules: {}
  scripts: {}
  server_modules: {}
